version: "3.7"

services:
  web:
    image: django_blog_app:v1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file: ./env/app/dev.env
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
      - ./mariadb_data_dev:/var/lib/mysql/
    env_file: ./env/db/db.dev.env
    ports:
      - 3306:3306

volumes:
  postgres_data_dev:
